In [1]:
import pandas as pd
from sklearn.datasets import fetch_openml

# download dataset from OpenML
bike = fetch_openml(name="Bike_Sharing_Demand", version=2, as_frame=True)

# features
X = bike.data

# target
y = bike.target

# combine into one dataframe
df = X.copy()
df["count"] = y

df.head()

,season,year,month,hour,holiday,weekday,workingday,weather,temp,feel_temp,humidity,windspeed,count
0,spring,0,1,0,False,6,False,clear,9.84,14.395,0.81,0.0,16
1,spring,0,1,1,False,6,False,clear,9.02,13.635,0.80,0.0,40
2,spring,0,1,2,False,6,False,clear,9.02,13.635,0.80,0.0,32
3,spring,0,1,3,False,6,False,clear,9.84,14.395,0.75,0.0,13
4,spring,0,1,4,False,6,False,clear,9.84,14.395,0.75,0.0,1

### Introduction: 

Bike-sharing provides a flexible, low-cost, and environmentally friendly alternative to traditional transport. However, the demand for bike rentals is not constant and is susceptible to external factors like weather conditions.

The objective of this project is to analyze how weather variables such as temperature, humidity, and wind speed affect the number of bike rentals. Understanding these relationships is key for forecasting bike-sharing systems. To achieve this, we use a dataset containing daily records of bike rentals along with weather-related variables. The analysis will proceed with data cleaning, exploratory data analysis through visualizations, and the application of a simple linear regression model to quantify the relationship between weather conditions and rental demand.

The main research question is:

**How do weather conditions influence the demand for bike-sharing?**

We aim to identify key factors that increase or decrease bike usage. Our explanatory variables will be weather-related variables such as temperature, humidity, and wind speed. The dependent variable will be the number of rentals.

### Inspecting the data and descriptive statistics

In [2]:
df.shape

(17379, 13)

In [3]:
df.columns

Index(['season', 'year', 'month', 'hour', 'holiday', 'weekday', 'workingday',
       'weather', 'temp', 'feel_temp', 'humidity', 'windspeed', 'count'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   season      17379 non-null  category
 1   year        17379 non-null  int64
 2   month       17379 non-null  int64
 3   hour        17379 non-null  int64
 4   holiday     17379 non-null  category
 5   weekday     17379 non-null  int64
 6   workingday  17379 non-null  category
 7   weather     17379 non-null  category
 8   temp        17379 non-null  float64
 9   feel_temp   17379 non-null  float64
 10  humidity    17379 non-null  float64
 11  windspeed   17379 non-null  float64
 12  count       17379 non-null  int64
dtypes: category(4), float64(4), int64(5)
memory usage: 1.3 MB

In [5]:
df.describe()

,year,month,hour,weekday,temp,feel_temp,humidity,windspeed,count
count,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000
mean,0.502561,6.537775,11.546752,3.003683,20.376474,23.788755,0.627229,12.736540,189.463088
std,0.500008,3.438776,6.914405,2.005771,7.894801,8.592511,0.192930,8.196795,181.387599
min,0.000000,1.000000,0.000000,0.000000,0.820000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,4.000000,6.000000,1.000000,13.940000,16.665000,0.480000,7.001500,40.000000
50%,1.000000,7.000000,12.000000,3.000000,20.500000,24.240000,0.630000,12.998000,142.000000
75%,1.000000,10.000000,18.000000,5.000000,27.060000,31.060000,0.780000,16.997900,281.000000
max,1.000000,12.000000,23.000000,6.000000,41.000000,50.000000,1.000000,56.996900,977.000000

#### Data Cleaning

We select the variables (columns) for temperature, humidity, windspeed, and the count of rentals.

In [7]:
df = df[["temp", "humidity", "windspeed", "count"]]
df.head()

   temp  humidity  windspeed  count
0  9.84      0.81        0.0     16
1  9.02      0.80        0.0     40
2  9.02      0.80        0.0     32
3  9.84      0.75        0.0     13
4  9.84      0.75        0.0      1

We check for missing values.

In [8]:
df.isnull().sum()

temp         0
humidity     0
windspeed    0
count        0
dtype: int64